import csv
import re
import sys
from pathlib import Path

ROOT = Path(r"c:\Users\Kudzanai\Documents\2025\App Developments\TrackHype")
CSV_PATH = ROOT / "trackhype_song_catalog.csv"
OUT_PATH = ROOT / "supabase" / "migrations" / "20260914_0005_seed_catalog.sql"

# Split only on feature markers. "&" is deliberately NOT split so band
# names like "Aphiwe & Sobancane" stay a single artist.
FEAT_RE = re.compile(r"\b(?:ft|feat)\.?|featuring", re.IGNORECASE)


def split_artists(raw):
    raw = FEAT_RE.sub(",", raw)
    parts = [re.sub(r"\s+", " ", p).strip().rstrip(",").strip() for p in raw.split(",")]
    return [p for p in parts if p]


def q(sql):
    return sql.replace("'", "''")


def main():
    songs, artists, relations, genres = [], [], [], []
    seen_artist = {}
    seen_song = set()

    # The demo catalog is comma-joined with NO quoting, and artist strings
    # themselves contain commas (e.g. "Dlala Thukzin, Funky QLA & Zee Nxumalo").
    # Structure per line is therefore: title, [artist...], genre, source, artwork.
    with open(CSV_PATH, encoding="utf-8-sig", newline="") as fh:
        reader = csv.reader(fh)
        fieldnames = next(reader)
        if fieldnames[0].strip().lower() != "title":
            raise SystemExit("Unexpected header: " + repr(fieldnames))
        for raw in reader:
            if not raw or not raw[0].strip():
                continue
            title = raw[0].strip()
            if not title or title.lower() == "title":
                continue
            artwork = raw[-1].strip()
            source = raw[-2].strip()
            genre = raw[-3].strip()
            artist_raw = ", ".join(p.strip() for p in raw[1:-3])
            if not genre or not artist_raw:
                continue

            key = title.lower()
            if key in seen_song:
                continue
            seen_song.add(key)
            songs.append((title, artwork, source))
            genres.append((title, genre))

            names = split_artists(artist_raw)
            for i, name in enumerate(names):
                lower = name.lower()
                if lower not in seen_artist:
                    seen_artist[lower] = name
                    artists.append(name)
                relations.append((title, name, i + 1, i > 0))

    lines = [
        "-- =============================================================",
        "-- TrackHype Phase 2 - seed: catalog from trackhype_song_catalog.csv",
        "-- Generated by supabase/seed_catalog.py - do not edit by hand.",
        "-- NOTE: run 0001-0004 first; genres/charts must exist for the joins.",
        "-- =============================================================",
        "",
    ]

    def vals(rows, ncols):
        rows = list(rows)
        return (
            ",\n".join("(" + ", ".join("'" + q(str(v)) + "'" for v in r) + ")" for r in rows)
            if rows
            else "NULL"
        )

    lines.append("-- ARTISTS")
    lines.append("insert into public.artists (name) values")
    lines.append(vals(([a] for a in artists), 1) + "\non conflict do nothing;")
    lines.append("")

    lines.append("-- SONGS (title, artwork, source)")
    lines.append("insert into public.songs (title, artwork, source) values")
    lines.append(vals(songs, 3) + "\non conflict do nothing;")
    lines.append("")

    lines.append("-- SONG_ARTISTS (primary = feature_order 1, rest featured)")
    lines.append("insert into public.song_artists (song_id, artist_id, feature_order, is_featured)")
    lines.append("select s.id, a.id, v.feature_order, v.is_featured")
    lines.append("from (values")
    lines.append(
        ",\n".join(
            "("
            + "'"
            + q(t)
            + "','"
            + q(an)
            + "',"
            + str(order)
            + ","
            + str(featured).lower()
            + ")"
            for t, an, order, featured in relations
        )
        + ") as v(title, artist, feature_order, is_featured)"
    )
    lines.append("join public.songs s on lower(s.title) = lower(v.title)")
    lines.append("join public.artists a on lower(a.name) = lower(v.artist)")
    lines.append("on conflict (song_id, artist_id) do nothing;")
    lines.append("")

    lines.append("-- SONG_GENRES")
    lines.append("insert into public.song_genres (song_id, genre_id)")
    lines.append("select s.id, g.id")
    lines.append("from (values")
    lines.append(",\n".join("('" + q(t) + "','" + q(g) + "')" for t, g in genres) + ") as v(title, genre)")
    lines.append("join public.songs s on lower(s.title) = lower(v.title)")
    lines.append("join public.genres g on lower(g.name) = lower(v.genre)")
    lines.append("on conflict (song_id, genre_id) do nothing;")
    lines.append("")

    OUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Artists: {len(artists)}  Songs: {len(songs)}  Relations: {len(relations)}")
    print(f"Wrote: {OUT_PATH}")
    print(f"Genre sweep: {sorted({g for _, g in genres})}")


if __name__ == "__main__":
    sys.exit(main())