var REGION_DIAL_CODES = {
  ZW: "+263",
  BW: "+267",
  ZA: "+27",
  AO: "+244",
  CD: "+243",
  KM: "+269",
  SZ: "+268",
  LS: "+266",
  MG: "+261",
  MW: "+265",
  MU: "+230",
  MZ: "+258",
  NA: "+264",
  SC: "+248",
  TZ: "+255",
  ZM: "+260",
  KE: "+254",
  NG: "+234",
  GH: "+233",
  UG: "+256",
  RW: "+250",
  BI: "+257",
  SS: "+211",
  SD: "+249",
  ET: "+251",
  EG: "+20",
  MA: "+212",
  DZ: "+213",
  TN: "+216",
  LY: "+218",
  CI: "+225",
  SN: "+221",
  CM: "+237",
  GB: "+44",
  US: "+1"
};

var REGION_NETWORKS = {
  ZW: ["Econet", "NetOne", "Telecel"],
  BW: ["Mascom", "Orange", "BTC", "beMobile"],
  ZA: ["Vodacom", "MTN", "Cell C", "Telkom"],
  EZ: [],
  SZ: ["MTN Eswatini", "Eswatini Mobile"],
  LS: ["Vodacom Lesotho", "ETL"],
  NA: ["MTC", "Telecom Namibia"],
  MW: ["Airtel", "TNM"],
  MZ: ["Vodacom", "Movitel", "TMCEL"],
  ZM: ["MTN", "Airtel", "Zamtel"],
  TZ: ["Vodacom", "Airtel", "Tigo", "TTCL", "Halotel"],
  KE: ["Safaricom", "Airtel", "Telkom Kenya"],
  UG: ["MTN", "Airtel", "Africell"],
  NG: ["MTN", "Airtel", "Globacom", "9mobile"],
  GH: ["MTN", "AT", "Telecel", "Glo"],
  ET: ["Ethio Telecom", "Safaricom Ethiopia"],
  GB: ["EE", "Vodafone", "O2", "Three"],
  US: ["AT&T", "Verizon", "T-Mobile"]
};

var REGION_TOWNS = {
  ZW: ["Harare", "Bulawayo", "Chitungwiza", "Gweru", "Mutare", "Kwekwe", "Kadoma", "Masvingo", "Zvishavane", "Bindura", "Marondera", "Hwange", "Victoria Falls", "Beitbridge", "Norton", "Chegutu", "Chinhoyi", "Rusape", "Kariba", "Chipinge"],
  BW: ["Gaborone", "Francistown", "Maun", "Molepolole", "Serowe", "Palapye", "Selebi-Phikwe", "Kanye", "Mochudi", "Lobatse", "Kasane", "Mahalapye", "Tlokweng", "Jwaneng", "Letlhakane"],
  ZA: ["Johannesburg", "Cape Town", "Durban", "Pretoria", "Port Elizabeth", "Bloemfontein", "East London"],
  MZ: ["Maputo", "Matola", "Beira", "Nampula", "Tete", "Xai-Xai", "Quelimane", "Chimoio"],
  ZM: ["Lusaka", "Kitwe", "Ndola", "Livingstone", "Kabwe", "Chipata"],
  MW: ["Lilongwe", "Blantyre", "Mzuzu", "Zomba", "Karonga"],
  TZ: ["Dar es Salaam", "Dodoma", "Mwanza", "Arusha", "Mbeya", "Morogoro"],
  KE: ["Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret"],
  NG: ["Lagos", "Abuja", "Port Harcourt", "Kano", "Ibadan", "Enugu"],
  GH: ["Accra", "Kumasi", "Tamale", "Takoradi", "Cape Coast"],
  UG: ["Kampala", "Entebbe", "Jinja", "Mbarara", "Gulu"],
  US: ["New York", "Los Angeles", "Chicago", "Houston", "Dallas", "Atlanta"],
  GB: ["London", "Birmingham", "Manchester", "Glasgow", "Leeds", "Bristol"]
};

var TOWN_AREAS = {
  "Harare": ["Avenues", "Borrowdale", "Budiriro", "Chisipite", "Eastlea", "Glen View", "Greendale", "Greystone Park", "Hatfield", "Highfield", "Highlands", "Mabvuku", "Marlborough", "Mbare", "Mount Pleasant", "Mufakose", "Newlands", "Southerton", "Sunningdale", "Waterfalls", "Westgate"],
  "Bulawayo": ["Belmont", "Bradfield", "Burnside", "Cowdray Park", "Emakhandeni", "Entumbane", "Family Park", "Hillside", "Khumalo", "Makokoba", "Malindela", "Nkulumane", "Nketa", "Parklands", "Pelandaba", "Queens Park", "Riverside", "Selbourne Park", "Suburbs", "Thorngrove"],
  "Chitungwiza": ["Seke", "Zengeza", "St Mary's", "Manyame Park", "Zimre Park"],
  "Gweru": ["Mkoba", "Senga", "Ascot", "Ivene", "Woodlands", "Southdowns", "Kopje", "Mtapa", "Ridgemont"],
  "Mutare": ["Dangamvura", "Sakubva", "Fairbridge Park", "Greenside", "Yeovil", "Westlea", "Hobhouse", "Christmas Pass"],
  "Kwekwe": ["Amaveni", "Mbizo", "Woodlands", "Surrey", "Torwood"],
  "Kadoma": ["Rimuka", "Central"],
  "Masvingo": ["Mucheke", "Rujeko", "Rhodene", "Morning Side"],
  "Zvishavane": ["Gulu", "Maglas", "Zvishavane Town"],
  "Bindura": ["Chipadze", "Chirorwe", "Svundura", "Farr Estate"],
  "Marondera": ["Dearme", "Westridge", "Chikowore"],
  "Hwange": ["Empress Mine", "Coolside", "Railway"],
  "Victoria Falls": ["Chinotimba", "Mkhosana", "CBD"],
  "Beitbridge": ["Dulivhadzimu", "Lutumba", "Longway"],
  "Norton": ["Wadzanai", "Norton Central"],
  "Chegutu": ["West End", "Town Centre"],
  "Chinhoyi": ["Mukome", "Eastlea", "Chinhoyi CBD"],
  "Rusape": ["Rujeko", "Seke Road", "Rusape Town"],
  "Kariba": ["Nyamhunga", "Mahombekombe", "Kariba Heights"],
  "Chipinge": ["Makoni", "Bondamakara", "Chipinge Town"],
  "Gaborone": ["Broadhurst", "Bontleng", "Extension 2", "Gaborone West", "Kgale", "Mokolodi", "Phakalane", "Tlokweng", "Village", "White City"],
  "Francistown": ["Monarch", "Area S", "Gerald Estate", "Block 5", "Ntsweng", "Tati Town"],
  "Maun": ["Disaneng", "Moeti", "Boseja", "Sedie"],
  "Molepolole": ["Majako", "Ngware", "Loologang"],
  "Serowe": ["Sekgoma", "Serowe North", "Serowe South"],
  "Palapye": ["Motshereganye", "Moremi", "Motsepha"],
  "Selebi-Phikwe": ["Central", "Bosele", "Senwamokgope"],
  "Kanye": ["Ganana", "Lorato", "Kanye Village"],
  "Mochudi": ["Pilane", "Molefi", "Kgaphamadi"],
  "Lobatse": ["Woodhall", "Peleng", "Old Town"],
  "Kasane": ["President Avenue", "Sedudu"],
  "Mahalapye": ["Botsalano", "Mahalapye Village"],
  "Tlokweng": ["Tlokweng Village", "Lesirane"],
  "Jwaneng": ["Jwaneng Town", "Central"],
  "Letlhakane": ["Letlhakane Village", "Botshabelo"]
};

var ONBOARDING_MOBILE_MONEY = ["EcoCash", "OneMoney", "TeleCash", "Other"];