window.ZIMBABWE_LOCATIONS_DATA = {
  "districts": [
    {
      "name": "Bulawayo",
      "code": "BUL",
      "towns": [
        {
          "name": "Bulawayo",
          "areas": [
            "Barbour Fields",
            "Bellevue",
            "Belmont",
            "Beverley",
            "Bradfield",
            "Burnside",
            "City Centre",
            "Colne Valley",
            "Cowdray Park",
            "Donnington",
            "Donnington West",
            "Emakhandeni",
            "Emganwini",
            "Emganwinin Ph 1",
            "Enqameni",
            "Enqotsheni",
            "Entumbane",
            "Fagodola",
            "Famona",
            "Fortune Gates",
            "Glencoe",
            "Glengarry",
            "Greenhill",
            "Gwabalanda",
            "Hillcrest",
            "Hlalani Kuhle",
            "Hume Park",
            "Hyde Park East",
            "Hyde Park Villa",
            "Ilanda",
            "Iminyela",
            "Intini",
            "Jacaranda",
            "Kelvin East",
            "Kelvin North",
            "Kelvin West",
            "Khumalo",
            "Killalo",
            "Killarney",
            "Kingsdale",
            "Lobengula",
            "Lobengula Ext",
            "Lochview",
            "Luveve",
            "Luveve Ext",
            "Luveve North",
            "Mabutweni",
            "Magwegwe",
            "Magwegwe West",
            "Mahatshula",
            "Mahatshula Sth",
            "Makokoba",
            "Malindela",
            "Manningdale",
            "Marklands",
            "Matsheumhlophe",
            "Matshobana",
            "Montgomery",
            "Morningside",
            "Mpopoma",
            "Mpopoma South",
            "Mqabuko Heights",
            "Mukuvisi Woodlands",
            "Mzilikazi",
            "New Luveve",
            "Newton",
            "Newton West",
            "Nguboyenja",
            "Njube",
            "Nketa",
            "Nkulumane",
            "North Trenance",
            "Ntaba Moyo",
            "Parklands",
            "Pumula A",
            "Pumula B",
            "Pumula C",
            "Pumula South",
            "Pumula South 1",
            "Queens Park Est",
            "Queens Park Wes",
            "Queensdale",
            "Richmond",
            "Richmond South",
            "Riverside",
            "Riverside North",
            "Riverside South",
            "Romney Park",
            "Sauerstown",
            "Sauerstown West",
            "Selbourne Park",
            "Sinyoka Village",
            "Sizinda",
            "Sunninghill",
            "Sunnyside",
            "Tegela",
            "The Jungle",
            "Thorngrove",
            "Thorngrove West",
            "Trenance",
            "Tshabalala",
            "Tshabalala Ext",
            "Umguza Estate",
            "Waterford",
            "Waterlea",
            "Willsgrove",
            "Woodlands",
            "Woodville"
          ]
        }
      ]
    },
    {
      "name": "Manicaland",
      "code": "MAN",
      "towns": [
        {
          "name": "Mutare",
          "areas": [
            "Avenues",
            "Bordervale",
            "Chikanga 1",
            "Chikanga 2",
            "Chikanga Ext.",
            "Chineta",
            "Chisamba Single",
            "Chitungo",
            "Dangamvura",
            "Destiny/Raheen",
            "Devonshire",
            "Dreamhouse",
            "Fairbridge",
            "Fern Valley",
            "Florida",
            "Garikai",
            "Greenside",
            "Hobhouse 1",
            "Hobhouse 3",
            "Hobhouse 4",
            "Hobhouse2",
            "Hospital Hill",
            "Industrial",
            "Macgrecors",
            "Magamba Township",
            "Magusha",
            "Maonde",
            "Matida/Mablocks/Chimoio",
            "Mazhambe",
            "Muchena",
            "Mundembe",
            "Murahwa Old Location",
            "Murambi",
            "Muteyo",
            "Natview",
            "New Chisamba",
            "Nhb",
            "Old Chisamba",
            "Palmerstone",
            "Sakubva",
            "Sakubva Sch",
            "St Josephs",
            "St Josephs Mission",
            "Tenderere",
            "Weirmouth",
            "Yeovil",
            "Zamba Sch",
            "Zimta",
            "Zororo",
            "Zororo 2"
          ]
        },
        {
          "name": "Buhera",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20",
            "Ward 21",
            "Ward 22",
            "Ward 23",
            "Ward 24",
            "Ward 25",
            "Ward 26",
            "Ward 27",
            "Ward 28",
            "Ward 29",
            "Ward 30",
            "Ward 31",
            "Ward 32",
            "Ward 33"
          ]
        },
        {
          "name": "Chimanimani",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20",
            "Ward 21",
            "Ward 22",
            "Ward 23"
          ]
        },
        {
          "name": "Chipinge",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20",
            "Ward 21",
            "Ward 22",
            "Ward 23",
            "Ward 24",
            "Ward 25",
            "Ward 26",
            "Ward 27",
            "Ward 28",
            "Ward 29",
            "Ward 30"
          ]
        },
        {
          "name": "Makoni",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20",
            "Ward 21",
            "Ward 22",
            "Ward 23",
            "Ward 24",
            "Ward 25",
            "Ward 26",
            "Ward 27",
            "Ward 28",
            "Ward 29",
            "Ward 30",
            "Ward 31",
            "Ward 32",
            "Ward 33",
            "Ward 34",
            "Ward 35",
            "Ward 36",
            "Ward 37",
            "Ward 38",
            "Ward 39"
          ]
        },
        {
          "name": "Mutasa",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20",
            "Ward 21",
            "Ward 22",
            "Ward 23",
            "Ward 24",
            "Ward 25",
            "Ward 26",
            "Ward 27",
            "Ward 28",
            "Ward 29",
            "Ward 30",
            "Ward 31"
          ]
        },
        {
          "name": "Nyanga",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20",
            "Ward 21",
            "Ward 22",
            "Ward 23",
            "Ward 24",
            "Ward 25",
            "Ward 26",
            "Ward 27",
            "Ward 28",
            "Ward 29",
            "Ward 30",
            "Ward 31"
          ]
        },
        {
          "name": "Rusape",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10"
          ]
        }
      ]
    },
    {
      "name": "Mashonaland Central",
      "code": "MSC",
      "towns": [
        {
          "name": "Bindura",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20",
            "Ward 21"
          ]
        },
        {
          "name": "Guruve",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20",
            "Ward 21",
            "Ward 22",
            "Ward 23",
            "Ward 24"
          ]
        },
        {
          "name": "Mazowe",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20",
            "Ward 21",
            "Ward 22",
            "Ward 23",
            "Ward 24",
            "Ward 25",
            "Ward 26",
            "Ward 27",
            "Ward 29",
            "Ward 30",
            "Ward 31",
            "Ward 32",
            "Ward 33",
            "Ward 34",
            "Ward 35"
          ]
        },
        {
          "name": "Mbire",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17"
          ]
        },
        {
          "name": "Mount Darwin",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20",
            "Ward 21",
            "Ward 22",
            "Ward 23",
            "Ward 24",
            "Ward 25",
            "Ward 26",
            "Ward 27",
            "Ward 28",
            "Ward 29",
            "Ward 30",
            "Ward 31",
            "Ward 32",
            "Ward 33",
            "Ward 34",
            "Ward 35",
            "Ward 36",
            "Ward 37",
            "Ward 38",
            "Ward 39",
            "Ward 40"
          ]
        },
        {
          "name": "Muzarabani",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20",
            "Ward 21",
            "Ward 22",
            "Ward 23",
            "Ward 24",
            "Ward 25",
            "Ward 26",
            "Ward 27",
            "Ward 28",
            "Ward 29"
          ]
        },
        {
          "name": "Mvurwi",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06"
          ]
        },
        {
          "name": "Rushinga",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20",
            "Ward 21",
            "Ward 22",
            "Ward 23",
            "Ward 24",
            "Ward 25"
          ]
        },
        {
          "name": "Shamva",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20",
            "Ward 21",
            "Ward 22",
            "Ward 23",
            "Ward 24",
            "Ward 25",
            "Ward 26",
            "Ward 27",
            "Ward 28",
            "Ward 29"
          ]
        }
      ]
    },
    {
      "name": "Mashonaland East",
      "code": "MSE",
      "towns": [
        {
          "name": "Marondera",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20",
            "Ward 21",
            "Ward 22",
            "Ward 23"
          ]
        },
        {
          "name": "Chikomba",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20",
            "Ward 21",
            "Ward 22",
            "Ward 23",
            "Ward 24",
            "Ward 25",
            "Ward 26",
            "Ward 27",
            "Ward 28",
            "Ward 29",
            "Ward 30"
          ]
        },
        {
          "name": "Goromonzi",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20",
            "Ward 21",
            "Ward 22",
            "Ward 23",
            "Ward 24",
            "Ward 25"
          ]
        },
        {
          "name": "Hwedza",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15"
          ]
        },
        {
          "name": "Mudzi",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18"
          ]
        },
        {
          "name": "Murehwa",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20",
            "Ward 21",
            "Ward 22",
            "Ward 23",
            "Ward 24",
            "Ward 25",
            "Ward 26",
            "Ward 27",
            "Ward 28",
            "Ward 29",
            "Ward 30"
          ]
        },
        {
          "name": "Mutoko",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20",
            "Ward 21",
            "Ward 22",
            "Ward 23",
            "Ward 24",
            "Ward 25",
            "Ward 26",
            "Ward 27",
            "Ward 28",
            "Ward 29"
          ]
        },
        {
          "name": "Ruwa Local Board",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09"
          ]
        },
        {
          "name": "Seke",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20",
            "Ward 21"
          ]
        },
        {
          "name": "Uzumba Maramba Pfungwe",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17"
          ]
        }
      ]
    },
    {
      "name": "Mashonaland West",
      "code": "MSW",
      "towns": [
        {
          "name": "Kadoma",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17"
          ]
        },
        {
          "name": "Chinhoyi",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15"
          ]
        },
        {
          "name": "Chegutu",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20",
            "Ward 21",
            "Ward 22",
            "Ward 23",
            "Ward 24",
            "Ward 25",
            "Ward 26",
            "Ward 27",
            "Ward 28",
            "Ward 29"
          ]
        },
        {
          "name": "Hurungwe",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20",
            "Ward 21",
            "Ward 22",
            "Ward 23",
            "Ward 24",
            "Ward 25",
            "Ward 26"
          ]
        },
        {
          "name": "Kariba",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12"
          ]
        },
        {
          "name": "Karoi",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10"
          ]
        },
        {
          "name": "Makonde",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19"
          ]
        },
        {
          "name": "Mhondoro-Ngezi",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16"
          ]
        },
        {
          "name": "Norton",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13"
          ]
        },
        {
          "name": "Sanyati",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18"
          ]
        },
        {
          "name": "Zvimba",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20",
            "Ward 21",
            "Ward 22",
            "Ward 23",
            "Ward 24",
            "Ward 25",
            "Ward 26",
            "Ward 27",
            "Ward 28",
            "Ward 29",
            "Ward 30",
            "Ward 31",
            "Ward 32",
            "Ward 33",
            "Ward 34",
            "Ward 35"
          ]
        }
      ]
    },
    {
      "name": "Matabeleland North",
      "code": "MBN",
      "towns": [
        {
          "name": "Binga",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20",
            "Ward 21",
            "Ward 22",
            "Ward 23",
            "Ward 24",
            "Ward 25"
          ]
        },
        {
          "name": "Bubi",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20",
            "Ward 21",
            "Ward 22",
            "Ward 23"
          ]
        },
        {
          "name": "Hwange",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20"
          ]
        },
        {
          "name": "Lupane",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20",
            "Ward 21",
            "Ward 22",
            "Ward 23",
            "Ward 24",
            "Ward 25",
            "Ward 26",
            "Ward 27",
            "Ward 28"
          ]
        },
        {
          "name": "Nkayi",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20",
            "Ward 21",
            "Ward 22",
            "Ward 23",
            "Ward 24",
            "Ward 25",
            "Ward 26",
            "Ward 27",
            "Ward 28",
            "Ward 29",
            "Ward 30"
          ]
        },
        {
          "name": "Tsholotsho",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20",
            "Ward 21",
            "Ward 22"
          ]
        },
        {
          "name": "Umguza",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19"
          ]
        },
        {
          "name": "Victoria Falls",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11"
          ]
        }
      ]
    },
    {
      "name": "Matabeleland South",
      "code": "MBS",
      "towns": [
        {
          "name": "Beitbridge",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15"
          ]
        },
        {
          "name": "Bulilima",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20",
            "Ward 21",
            "Ward 22"
          ]
        },
        {
          "name": "Gwanda",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20",
            "Ward 21",
            "Ward 22",
            "Ward 23",
            "Ward 24"
          ]
        },
        {
          "name": "Insiza",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20",
            "Ward 21",
            "Ward 22",
            "Ward 23"
          ]
        },
        {
          "name": "Mangwe",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17"
          ]
        },
        {
          "name": "Matobo",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20",
            "Ward 21",
            "Ward 22",
            "Ward 23",
            "Ward 24",
            "Ward 25"
          ]
        },
        {
          "name": "Plumtree",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06"
          ]
        },
        {
          "name": "Umzingwane",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20"
          ]
        }
      ]
    },
    {
      "name": "Midlands",
      "code": "MID",
      "towns": [
        {
          "name": "Gweru",
          "areas": [
            "Airforce",
            "Ascot Ext",
            "Ascot Infill",
            "Batanai",
            "Bickford",
            "Brackenhurst",
            "Coolmoreen",
            "Daylesford",
            "Greenvale",
            "Gweru East",
            "Hertfordshire",
            "Ivene",
            "Kingston Park",
            "Kopje",
            "Lundi",
            "Mambo",
            "Mkoba 1",
            "Mkoba 1 Police",
            "Mkoba 1 Police Camp",
            "Mkoba 10",
            "Mkoba 11",
            "Mkoba 12",
            "Mkoba 12 Light Industry",
            "Mkoba 13",
            "Mkoba 14",
            "Mkoba 15",
            "Mkoba 16",
            "Mkoba 17",
            "Mkoba 18",
            "Mkoba 19",
            "Mkoba 2",
            "Mkoba 20",
            "Mkoba 3",
            "Mkoba 4",
            "Mkoba 5",
            "Mkoba 6",
            "Mkoba 7",
            "Mkoba 8",
            "Mkoba 9",
            "Mkoba Industry",
            "Mkoba Teachers",
            "Mkoba1",
            "Mkoba11",
            "Montrose",
            "Msu Campus 2",
            "Msu Main Campus",
            "Mtapa",
            "Nashiville",
            "Nehosho",
            "Nothlea",
            "Old Ascot",
            "Ridgemont",
            "Ridgemont Heights",
            "Senga",
            "Shamrock Park",
            "Southdowns",
            "Target Kopje",
            "Windsor Park"
          ]
        },
        {
          "name": "Kwekwe",
          "areas": [
            "Amaveni",
            "Chicago Plots",
            "Fitchlea",
            "Gaika Mine",
            "Globe And Phoenix",
            "Golden Acres",
            "Kwekwe Polytechnic",
            "Kwekwe Town",
            "Mbizo 1",
            "Mbizo 1 Ext",
            "Mbizo 10",
            "Mbizo 10 Ext",
            "Mbizo 11",
            "Mbizo 12",
            "Mbizo 13",
            "Mbizo 14",
            "Mbizo 15",
            "Mbizo 16",
            "Mbizo 16 Ext",
            "Mbizo 17",
            "Mbizo 17 Ext",
            "Mbizo 18",
            "Mbizo 19",
            "Mbizo 2 (Me)",
            "Mbizo 20",
            "Mbizo 21",
            "Mbizo 22",
            "Mbizo 3",
            "Mbizo 4",
            "Mbizo 5",
            "Mbizo 6",
            "Mbizo 7",
            "Mbizo 8",
            "Mbizo 8 Ext",
            "Mbizo 9",
            "Mbizo 9 Ext",
            "Mbizo Stadium",
            "Rutendo"
          ]
        },
        {
          "name": "Chirumanzu",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20",
            "Ward 21",
            "Ward 22",
            "Ward 23",
            "Ward 24",
            "Ward 25"
          ]
        },
        {
          "name": "Gokwe North",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20",
            "Ward 21",
            "Ward 22",
            "Ward 23",
            "Ward 24",
            "Ward 25",
            "Ward 26",
            "Ward 27",
            "Ward 28",
            "Ward 29",
            "Ward 30",
            "Ward 31",
            "Ward 32",
            "Ward 33",
            "Ward 34",
            "Ward 35",
            "Ward 36"
          ]
        },
        {
          "name": "Gokwe South",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20",
            "Ward 21",
            "Ward 22",
            "Ward 23",
            "Ward 24",
            "Ward 25",
            "Ward 26",
            "Ward 27",
            "Ward 28",
            "Ward 29",
            "Ward 30",
            "Ward 31",
            "Ward 32",
            "Ward 33"
          ]
        },
        {
          "name": "Gokwe Town Centre",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06"
          ]
        },
        {
          "name": "Mberengwa",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20",
            "Ward 21",
            "Ward 22",
            "Ward 23",
            "Ward 24",
            "Ward 25",
            "Ward 26",
            "Ward 27",
            "Ward 28",
            "Ward 29",
            "Ward 30",
            "Ward 31",
            "Ward 32",
            "Ward 33",
            "Ward 34",
            "Ward 35",
            "Ward 36",
            "Ward 37"
          ]
        },
        {
          "name": "Redcliff",
          "areas": [
            "Millenium Park",
            "Redcliff",
            "Simbi Park",
            "Torwood"
          ]
        },
        {
          "name": "Shurugwi",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20",
            "Ward 21",
            "Ward 22",
            "Ward 23",
            "Ward 24"
          ]
        },
        {
          "name": "Zvishavane",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19"
          ]
        }
      ]
    },
    {
      "name": "Masvingo",
      "code": "MVG",
      "towns": [
        {
          "name": "Masvingo",
          "areas": [
            "Eastvale",
            "Mucheke",
            "Rujeko"
          ]
        },
        {
          "name": "Bikita",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20",
            "Ward 21",
            "Ward 22",
            "Ward 23",
            "Ward 24",
            "Ward 25",
            "Ward 26",
            "Ward 27",
            "Ward 28",
            "Ward 29",
            "Ward 30",
            "Ward 31",
            "Ward 32"
          ]
        },
        {
          "name": "Chiredzi",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20",
            "Ward 21",
            "Ward 22",
            "Ward 23",
            "Ward 24",
            "Ward 25",
            "Ward 26",
            "Ward 27",
            "Ward 28",
            "Ward 29",
            "Ward 30",
            "Ward 31",
            "Ward 32"
          ]
        },
        {
          "name": "Chivi",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20",
            "Ward 21",
            "Ward 22",
            "Ward 23",
            "Ward 24",
            "Ward 25",
            "Ward 26",
            "Ward 27",
            "Ward 28",
            "Ward 29",
            "Ward 30",
            "Ward 31",
            "Ward 32"
          ]
        },
        {
          "name": "Gutu",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20",
            "Ward 21",
            "Ward 22",
            "Ward 23",
            "Ward 24",
            "Ward 25",
            "Ward 26",
            "Ward 27",
            "Ward 28",
            "Ward 29",
            "Ward 30",
            "Ward 31",
            "Ward 32",
            "Ward 33",
            "Ward 34",
            "Ward 35",
            "Ward 36",
            "Ward 37",
            "Ward 38",
            "Ward 39",
            "Ward 40",
            "Ward 41"
          ]
        },
        {
          "name": "Mwenezi",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18"
          ]
        },
        {
          "name": "Zaka",
          "areas": [
            "Ward 01",
            "Ward 02",
            "Ward 03",
            "Ward 04",
            "Ward 05",
            "Ward 06",
            "Ward 07",
            "Ward 08",
            "Ward 09",
            "Ward 10",
            "Ward 11",
            "Ward 12",
            "Ward 13",
            "Ward 14",
            "Ward 15",
            "Ward 16",
            "Ward 17",
            "Ward 18",
            "Ward 19",
            "Ward 20",
            "Ward 21",
            "Ward 22",
            "Ward 23",
            "Ward 24",
            "Ward 25",
            "Ward 26",
            "Ward 27",
            "Ward 28",
            "Ward 29",
            "Ward 30",
            "Ward 31",
            "Ward 32",
            "Ward 33",
            "Ward 34"
          ]
        }
      ]
    },
    {
      "name": "Harare",
      "code": "HAR",
      "towns": [
        {
          "name": "Harare",
          "areas": [
            "Adylinn",
            "Airport",
            "Amby",
            "Arlington",
            "Ashdown Park",
            "Aspindale",
            "Athlone",
            "Avondale",
            "Belvedere",
            "Beverly West",
            "Bluffhill",
            "Borrowdale",
            "Borrowdale Brooke",
            "Braeside",
            "Budiriro",
            "Caledonia",
            "Carrick Creagh",
            "Chadcombe",
            "Chikurubi",
            "Chiltern Hills",
            "Chisipite",
            "Christmas Gift",
            "Cleveland Dam",
            "Colray",
            "Cranborne Park",
            "Crowborough",
            "Darlington",
            "Dzivaresekwa",
            "Dzivaresekwa Ext",
            "Eastlea",
            "Emerald Hill",
            "Glaudina",
            "Glen Lorne",
            "Granary Phase 1",
            "Granary Phase 2",
            "Granary Phase 3",
            "Granary Phase 4",
            "Graniteside",
            "Greendale",
            "Groombridge",
            "Gunhill",
            "Hatcliffe",
            "Hatfield",
            "Hatfield B",
            "Helensvale",
            "Highfield",
            "Highlands",
            "Hopley",
            "Kambanji",
            "Kambuzuma",
            "Kuwadzana",
            "Lichendale",
            "Mabelreign",
            "Mabvuku",
            "Mainway Meadows",
            "Mandara",
            "Marlborough",
            "Mbare",
            "Monavale",
            "Msasa Ind",
            "Msasa Industry",
            "Msasa Park",
            "Mufakose",
            "Northwood",
            "Oval Park",
            "Parktown",
            "Pomona",
            "Prospect",
            "Rolf Valley",
            "Rugare",
            "Southerton",
            "St Martins",
            "Stone Ridge",
            "Sunningdale",
            "Sunridge",
            "Tafara",
            "The Grange",
            "Tynwald North",
            "Tynwald South",
            "Umwinsidale",
            "Vainona",
            "Warren Park",
            "Waterfalls",
            "Westend",
            "Westgate",
            "Westlea",
            "Westwood",
            "Wild Geese"
          ]
        },
        {
          "name": "Chitungwiza",
          "areas": [
            "Chitungwiza",
            "Firle Area",
            "Manyame",
            "Unit A",
            "Unit J",
            "Zengeza 4"
          ]
        },
        {
          "name": "Epworth",
          "areas": [
            "Epworth"
          ]
        }
      ]
    }
  ]
};
