-- =============================================================
-- TrackHype Phase 2 — seed: radio stations (all 21, as shipped
-- in radio-data.js incl. Botswana) + placeholder adverts.
-- =============================================================

insert into public.radio_stations (id, name, country, region, freq, logo, focus) values
  ('radio-zimbabwe',  'Radio Zimbabwe',      'Zimbabwe', 'National (Public)',   null,       'Assets/logos/Radio Stations/Zimbabwe_Radio_Stations/Radio_Zimbabwe_Logo.jpg',                     'Local languages, Zimbabwean culture and community news; Sungura, Gospel, Chimurenga and traditional music.'),
  ('power-fm',        'Power FM',            'Zimbabwe', 'National (Public)',   null,       'Assets/logos/Radio Stations/Zimbabwe_Radio_Stations/Power_FM_Logo.jpg',                             'National urban contemporary station targeted at youth: Zimdancehall, Zim Hip Hop, Afro-pop and urban contemporary hits.'),
  ('national-fm',     'National FM',         'Zimbabwe', 'National (Public)',   null,       'Assets/logos/Radio Stations/Zimbabwe_Radio_Stations/National_FM_Logo.jpg',                          'Dedicated entirely to minority languages, indigenous traditions and ethnic cultural programming.'),
  ('classic-263',     'Classic 263',         'Zimbabwe', 'National (Public)',   null,       'Assets/logos/Radio Stations/Zimbabwe_Radio_Stations/Classic_263_FM_Logo.jpg',                       'Talk radio, current affairs and classic music (formerly Spot FM/SFM).'),
  ('star-fm',         'Star FM',             'Zimbabwe', 'National (Commercial)', '89.7 MHz', 'Assets/logos/Radio Stations/Zimbabwe_Radio_Stations/Star_fm_logo.jpg',                             'Zimbabwe''s first commercial station, catering to urban youth, contemporary pop and mainstream hits.'),
  ('zifm-stereo',     'ZiFM Stereo',         'Zimbabwe', 'National (Commercial)', '106.1 MHz','Assets/logos/Radio Stations/Zimbabwe_Radio_Stations/zifm_logo.png',                              'The country''s first privately owned urban music and talk station — global pop, regional hits and polished local productions.'),
  ('capitalk',        'Capitalk 100.4 FM',   'Zimbabwe', 'Harare',               '100.4 MHz', 'Assets/logos/Radio Stations/Zimbabwe_Radio_Stations/Capitalk__FM_logo.png',                        'Capital city talk radio, news and current affairs.'),
  ('skyz-metro',      'Skyz Metro FM',       'Zimbabwe', 'Bulawayo',             '100.3 MHz', 'Assets/logos/Radio Stations/Zimbabwe_Radio_Stations/Skyz Metro FM.png',                             'Bulawayo urban culture and music.'),
  ('khulumani',       'Khulumani FM',        'Zimbabwe', 'Bulawayo',             '95.0 MHz',  'Assets/logos/Radio Stations/Zimbabwe_Radio_Stations/Khulumani_FM_logo.jpg',                          'The broader Bulawayo metropolitan community.'),
  ('diamond-fm',      'Diamond FM',          'Zimbabwe', 'Mutare (Manicaland)',  '103.8 MHz', 'Assets/logos/Radio Stations/Zimbabwe_Radio_Stations/Diamond_FM_logo.png',                          'Regional coverage for the Manicaland province.'),
  ('midlands-984',    '98.4 Midlands',       'Zimbabwe', 'Gweru (Midlands)',     '98.4 MHz',  'Assets/logos/Radio Stations/Zimbabwe_Radio_Stations/984_Midlands_FM_Logo.png',                       'Youth, contemporary music and local entertainment.'),
  ('central-958',     '95.8 Central Radio',  'Zimbabwe', 'Gweru (Midlands)',     '95.8 MHz',  'Assets/logos/Radio Stations/Zimbabwe_Radio_Stations/958_ Central_Radio_FM_Logo.jpg',                'Commercial talk and local news for the Midlands area.'),
  ('breeze-fm',       'Breeze FM',           'Zimbabwe', 'Victoria Falls',       '91.2 MHz',  'Assets/logos/Radio Stations/Zimbabwe_Radio_Stations/Breeze_FM_logo.jpg',                             'Victoria Falls tourism hub and local community news.'),
  ('yafm',            'YAFM',                'Zimbabwe', 'Zvishavane',           '91.8 MHz',  'Assets/logos/Radio Stations/Zimbabwe_Radio_Stations/YAFM_FM_logo.jpg',                               'Tailored around the mining community, local news and music.'),
  ('hevoi-fm',        'Hevoi FM',            'Zimbabwe', 'Masvingo',             '100.2 MHz', 'Assets/logos/Radio Stations/Zimbabwe_Radio_Stations/Hevoi_FM_Logo.jpg',                               'Masvingo provincial news and regional programming.'),
  ('nyaminyami-fm',   'Nyaminyami FM',       'Zimbabwe', 'Kariba (Zambezi Valley)', '94.5 MHz','Assets/logos/Radio Stations/Zimbabwe_Radio_Stations/Nyaminyami_FM_Logo.jpg',                     'Serves the Zambezi Valley community with local content.'),
  ('rb1',             'Radio Botswana 1 (RB1)', 'Botswana', 'National (Public)', null,      'Assets/logos/Radio Stations/Botswana_Radio_Stations/Radio_Botswana_1-RB1_FM_Logo.jpg',            'National heritage, agricultural programming, news and traditional folk rhythms (Setapa, Borankana, Dikwaere).'),
  ('rb2',             'Radio Botswana 2 (RB2)', 'Botswana', 'National (Public)', null,      'Assets/logos/Radio Stations/Botswana_Radio_Stations/Radio_Botswana_2_(RB2)_FM_Logo.jpg',          'Commercial youth wing of state broadcasting: pop, Amapiano, Afro-house, Hip Hop and local urban tracks.'),
  ('yarona-fm',       'Yarona FM',           'Botswana', 'Gaborone',             '106.6 FM',  'Assets/logos/Radio Stations/Botswana_Radio_Stations/Yarona_FM_Logo.jpg',                             'Gaborone''s urban youth station: Motswako, Hip-Hop, Amapiano and pop chart-toppers.'),
  ('gabz-fm',         'Gabz FM',             'Botswana', 'Gaborone',             '96.2 FM',   'Assets/logos/Radio Stations/Botswana_Radio_Stations/Gabz_FM_Logo.png',                               'Adult contemporary station for mature professionals: talk shows, jazz, soul and classic hits.'),
  ('duma-fm',         'Duma FM',             'Botswana', 'National (Commercial)', '93.0 FM',  'Assets/logos/Radio Stations/Botswana_Radio_Stations/Duma_FM_Logo.jpg',                              'Family-oriented commercial station balancing talk radio, news and diverse music genres.');

insert into public.adverts (title, image, link, placement, is_active) values
  ('DemoPlacement — Carousel 1', null, 'https://trackhype.example', 'recent-charts', true);